title: Fun Q
description: "Source files for \"Fun Q: A Functional Introduction to Machine Learning in Q\""
google_analytics:
show_downloads: false
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
